# classes = [
#     'forest',
#     'permanent crop land',
#     'residential buildings or homes or apartments',
#     'river',
#     'pasture land',
#     'lake or sea',
#     'brushland or shrubland',
#     'annual crop land',
#     'industrial buildings or commercial buildings',
#     'highway or road',
# ]
# ['River', 'AnnualCrop', 'HerbaceousVegetation', 'Industrial', 'Residential', 'Highway', 'Pasture', 'Forest', 'SeaLake', 'PermanentCrop']

classes = [
    'river',
    'crop land',
    'brushland or shrubland',
    'industrial buildings or commercial buildings',
    'residential buildings or homes or apartments',
    'highway or road',
    'pasture land',
    'forest',
    'lake or sea',
    'permanent crop land',
]

# templates = [
#     'a centered satellite photo of {}.',
#     'a centered satellite photo of a {}.',
#     'a centered satellite photo of the {}.',
# ]

# templates = [
#     'a satellite image of {}.',
#     'a centered satellite photo of a {}.',
#     'satellite view of a {}.',
#     'satellite view of the {}.',
#     'a centered satellite photo of the {}.',
#     'satellite photo of the {}.',
#     'a centered satellite photo of {}.',
#     'satellite view of {}.',
#     'satellite photo of a {}.',
#     'a satellite photo of {}.',
#     'a remote sensing image of many {}.',
#     'a remote sensing image of a {}.',
#     'a remote sensing image of the {}.',
#     'a remote sensing image of the hard to see {}.',
#     'a remote sensing image of a hard to see {}.',
#     'a low resolution remote sensing image of the {}.',
#     'a low resolution remote sensing image of a {}.',
#     'a bad remote sensing image of the {}.',
#     'a bad remote sensing image of a {}.',
#     'a cropped remote sensing image of the {}.',
#     'a cropped remote sensing image of a {}.',
#     'a bright remote sensing image of the {}.',
#     'a bright remote sensing image of a {}.',
#     'a dark remote sensing image of the {}.',
#     'a dark remote sensing image of a {}.',
#     'a close-up remote sensing image of the {}.',
#     'a close-up remote sensing image of a {}.',
#     'a black and white remote sensing image of the {}.',
#     'a black and white remote sensing image of a {}.',
#     'a jpeg corrupted remote sensing image of the {}.',
#     'a jpeg corrupted remote sensing image of a {}.',
#     'a blurry remote sensing image of the {}.',
#     'a blurry remote sensing image of a {}.',
#     'a good remote sensing image of the {}.',
#     'a good remote sensing image of a {}.',
#     'a remote sensing image of the large {}.',
#     'a remote sensing image of a large {}.',
#     'a remote sensing image of the nice {}.',
#     'a remote sensing image of a nice {}.',
#     'a remote sensing image of the small {}.',
#     'a remote sensing image of a small {}.',
#     'a remote sensing image of the weird {}.',
#     'a remote sensing image of a weird {}.',
#     'a remote sensing image of the cool {}.',
#     'a remote sensing image of a cool {}.',
#     'an aerial image of many {}.',
#     'an aerial image of a {}.',
#     'an aerial image of the {}.',
#     'an aerial image of the hard to see {}.',
#     'an aerial image of a hard to see {}.',
#     'a low resolution aerial image of the {}.',
#     'a low resolution aerial image of a {}.',
#     'a bad aerial image of the {}.',
#     'a bad aerial image of a {}.',
#     'a cropped aerial image of the {}.',
#     'a cropped aerial image of a {}.',
#     'a bright aerial image of the {}.',
#     'a bright aerial image of a {}.',
#     'a dark aerial image of the {}.',
#     'a dark aerial image of a {}.',
#     'a close-up aerial image of the {}.',
#     'a close-up aerial image of a {}.',
#     'a black and white aerial image of the {}.',
#     'a black and white aerial image of a {}.',
#     'a jpeg corrupted aerial image of the {}.',
#     'a jpeg corrupted aerial image of a {}.',
#     'a blurry aerial image of the {}.',
#     'a blurry aerial image of a {}.',
#     'a good aerial image of the {}.',
#     'a good aerial image of a {}.',
#     'an aerial image of the large {}.',
#     'an aerial image of a large {}.',
#     'an aerial image of the nice {}.',
#     'an aerial image of a nice {}.',
#     'an aerial image of the small {}.',
#     'an aerial image of a small {}.',
#     'an aerial image of the weird {}.',
#     'an aerial image of a weird {}.',
#     'an aerial image of the cool {}.',
#     'an aerial image of a cool {}.',
#     'a satellite image of many {}.',
#     'a satellite image of a {}.',
#     'a satellite image of the {}.',
#     'a satellite image of the hard to see {}.',
#     'a satellite image of a hard to see {}.',
#     'a low resolution satellite image of the {}.',
#     'a low resolution satellite image of a {}.',
#     'a bad satellite image of the {}.',
#     'a bad satellite image of a {}.',
#     'a cropped satellite image of the {}.',
#     'a cropped satellite image of a {}.',
#     'a bright satellite image of the {}.',
#     'a bright satellite image of a {}.',
#     'a dark satellite image of the {}.',
#     'a dark satellite image of a {}.',
#     'a close-up satellite image of the {}.',
#     'a close-up satellite image of a {}.',
#     'a black and white satellite image of the {}.',
#     'a black and white satellite image of a {}.',
#     'a jpeg corrupted satellite image of the {}.',
#     'a jpeg corrupted satellite image of a {}.',
#     'a blurry satellite image of the {}.',
#     'a blurry satellite image of a {}.',
#     'a good satellite image of the {}.',
#     'a good satellite image of a {}.',
#     'a satellite image of the large {}.',
#     'a satellite image of a large {}.',
#     'a satellite image of the nice {}.',
#     'a satellite image of a nice {}.',
#     'a satellite image of the small {}.',
#     'a satellite image of a small {}.',
#     'a satellite image of the weird {}.',
#     'a satellite image of a weird {}.',
#     'a satellite image of the cool {}.',
#     'a satellite image of a cool {}.',
# ]

templates = [
    'a centered satellite photo of {c}.',
    'a centered satellite photo of a {c}.',
    'a centered satellite photo of the {c}.',
    'an aerial view of {c}.',
    'an aerial view of a {c}.',
    'an aerial view of the {c}.',
    'a satellite image showing {c}.',
    'a satellite image showing a {c}.',
    'a satellite image showing the {c}.',
    'a remote sensing image of {c}.',
    'a remote sensing image of a {c}.',
    'a remote sensing image of the {c}.',
    'aerial imagery depicting {c}.',
    'aerial imagery depicting a {c}.',
    'aerial imagery depicting the {c}.',
    'a satellite capture of {c}.',
    'a satellite capture of a {c}.',
    'a satellite capture of the {c}.',
    'a remote capture of {c}.',
    'a remote capture of a {c}.',
    'a remote capture of the {c}.',
    'a satellite shot of {c}.',
    'a satellite shot of a {c}.',
    'a satellite shot of the {c}.',
    'a remote photo of {c}.',
    'a remote photo of a {c}.',
    'a remote photo of the {c}.',
    'an above-ground photo of {c}.',
    'an above-ground photo of a {c}.',
    'an above-ground photo of the {c}.',
    'a satellite image of {c}.',
    'a centered satellite photo of a {c}.',
    'satellite view of a {c}.',
    'satellite view of the {c}.',
    'a centered satellite photo of the {c}.',
    'satellite photo of the {c}.',
    'a centered satellite photo of {c}.',
    'satellite view of {c}.',
    'satellite photo of a {c}.',
    'a satellite photo of {c}.',
    'a remote sensing image of many {c}.',
    'a remote sensing image of a {c}.',
    'a remote sensing image of the {c}.',
    'a remote sensing image of the hard to see {c}.',
    'a remote sensing image of a hard to see {c}.',
    'a low resolution remote sensing image of the {c}.',
    'a low resolution remote sensing image of a {c}.',
    'a bad remote sensing image of the {c}.',
    'a bad remote sensing image of a {c}.',
    'a cropped remote sensing image of the {c}.',
    'a cropped remote sensing image of a {c}.',
    'a bright remote sensing image of the {c}.',
    'a bright remote sensing image of a {c}.',
    'a dark remote sensing image of the {c}.',
    'a dark remote sensing image of a {c}.',
    'a close-up remote sensing image of the {c}.',
    'a close-up remote sensing image of a {c}.',
    'a black and white remote sensing image of the {c}.',
    'a black and white remote sensing image of a {c}.',
    'a jpeg corrupted remote sensing image of the {c}.',
    'a jpeg corrupted remote sensing image of a {c}.',
    'a blurry remote sensing image of the {c}.',
    'a blurry remote sensing image of a {c}.',
    'a good remote sensing image of the {c}.',
    'a good remote sensing image of a {c}.',
    'a remote sensing image of the large {c}.',
    'a remote sensing image of a large {c}.',
    'a remote sensing image of the nice {c}.',
    'a remote sensing image of a nice {c}.',
    'a remote sensing image of the small {c}.',
    'a remote sensing image of a small {c}.',
    'a remote sensing image of the weird {c}.',
    'a remote sensing image of a weird {c}.',
    'a remote sensing image of the cool {c}.',
    'a remote sensing image of a cool {c}.',
    'an aerial image of many {c}.',
    'an aerial image of a {c}.',
    'an aerial image of the {c}.',
    'an aerial image of the hard to see {c}.',
    'an aerial image of a hard to see {c}.',
    'a low resolution aerial image of the {c}.',
    'a low resolution aerial image of a {c}.',
    'a bad aerial image of the {c}.',
    'a bad aerial image of a {c}.',
    'a cropped aerial image of the {c}.',
    'a cropped aerial image of a {c}.',
    'a bright aerial image of the {c}.',
    'a bright aerial image of a {c}.',
    'a dark aerial image of the {c}.',
    'a dark aerial image of a {c}.',
    'a close-up aerial image of the {c}.',
    'a close-up aerial image of a {c}.',
    'a black and white aerial image of the {c}.',
    'a black and white aerial image of a {c}.',
    'a jpeg corrupted aerial image of the {c}.',
    'a jpeg corrupted aerial image of a {c}.',
    'a blurry aerial image of the {c}.',
    'a blurry aerial image of a {c}.',
    'a good aerial image of the {c}.',
    'a good aerial image of a {c}.',
    'an aerial image of the large {c}.',
    'an aerial image of a large {c}.',
    'an aerial image of the nice {c}.',
    'an aerial image of a nice {c}.',
    'an aerial image of the small {c}.',
    'an aerial image of a small {c}.',
    'an aerial image of the weird {c}.',
    'an aerial image of a weird {c}.',
    'an aerial image of the cool {c}.',
    'an aerial image of a cool {c}.',
    'a satellite image of many {c}.',
    'a satellite image of a {c}.',
    'a satellite image of the {c}.',
    'a satellite image of the hard to see {c}.',
    'a satellite image of a hard to see {c}.',
    'a low resolution satellite image of the {c}.',
    'a low resolution satellite image of a {c}.',
    'a bad satellite image of the {c}.',
    'a bad satellite image of a {c}.',
    'a cropped satellite image of the {c}.',
    'a cropped satellite image of a {c}.',
    'a bright satellite image of the {c}.',
    'a bright satellite image of a {c}.',
    'a dark satellite image of the {c}.',
    'a dark satellite image of a {c}.',
    'a close-up satellite image of the {c}.',
    'a close-up satellite image of a {c}.',
    'a black and white satellite image of the {c}.',
    'a black and white satellite image of a {c}.',
    'a jpeg corrupted satellite image of the {c}.',
    'a jpeg corrupted satellite image of a {c}.',
    'a blurry satellite image of the {c}.',
    'a blurry satellite image of a {c}.',
    'a good satellite image of the {c}.',
    'a good satellite image of a {c}.',
    'a satellite image of the large {c}.',
    'a satellite image of a large {c}.',
    'a satellite image of the nice {c}.',
    'a satellite image of a nice {c}.',
    'a satellite image of the small {c}.',
    'a satellite image of a small {c}.',
    'a satellite image of the weird {c}.',
    'a satellite image of a weird {c}.',
    'a satellite image of the cool {c}.',
    'a satellite image of a cool {c}.',
]
